# Site settings
title: Kevin Ma
description: > #
  Kevin is a Software Designer in New York
baseurl: ""
url: "https://kevthema.com" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
include: ['_pages']
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - node_modules

# Collections
collections:
  project:
    output: true
    permalink: /projects/:path/

# Plugin settings
gems:
  - jekyll-feed
  - jekyll-sitemap
